name : My first workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name : Clone repo
        uses: actions/checkout@v6
      - name: My first job
        run:
          echo "Bonjour tout le monde"
          ls -ltra
          cat README.md
      - name : Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover , I am a DRAGON....RAWR" >> dragon.txt
